name: convolution-workshop
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - pillow>=8.3.0
  - ipywidgets>=7.6.0
  - jupyter>=1.0.0
  - pip
  - pip:
    - ipython